config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:create, :destroy, :new]

  resources :questions do
    resources :answers, except: [:index, :show]
    resources :comments, except: [:show,:index]
  end

  resources :answers, except: [:index, :show] do
    resources :comments
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/question.rb
class Question < ActiveRecord::Base

  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = Question.find(params[:question_id])
    if @answer.save
      redirect_to question_path(@answer.question)
    else
      render :new
    end
  end

  # def edit
  #   @answer = Answer.find(params[:id])
  #   @question = @answer.question
  # end

  # def update
  #   @answer = Answer.find(params[:id])
  #   if @answer.update(answer_params)
  #     redirect_to question_path(@answer.question)
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    answer = Answer.find(params[:id])
    question = answer.question
    answer.delete

    redirect_to question_path(question)
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!session[:user_id]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :require_login, only: [:new, :create]

  def new
    @comment = Comment.new
  end

  def create
    resource = if params[:question_id]
      Question.find(params[:question_id])
    else
      Answer.find(params[:answer_id])
    end

    comment = resource.comments.build comment_params.merge(user: current_user)

    if comment.save
      flash[:success] = "Comment is created."
      redirect_to redirect_url_after_create resource
    else
      flash[:error] = "Comment can't be created."
      redirect_to redirect_url_after_create resource
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:response)
  end

  def redirect_url_after_create resource
    resource.is_a?(Answer) ? question_path(resource.question) : resource
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # before_action :require_login, only: [:new, :create]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to :root
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.includes(:user)
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    question = Question.find(params[:id])
    if question.delete
      redirect_to :root
    else
      render :index
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :root
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @new_user = User.new
  end

  def create
    @new_user = User.new(user_params)
    if @new_user.save
      session[:user_id] = @new_user.id
      redirect_to :root
    else
      render new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
  <div>
    <%= answer.content %>
    <% if current_user == answer.user %>
    <%= link_to 'delete', "/questions/#{answer.question.id}/answers/#{answer.id}", method: :delete %>
    <% end %>
  </div>

  <div>
    by <%= answer.user.username %>
  <div>

  <div>
    <%= render partial: 'comments/form', locals: {resource: answer, comment: Comment.new} %>
  </div>


  <div>
    <%=render partial: "comments/comment", locals: {comments: answer.comments}%>
  </div>

app/views/answers/new.html.erb
<%= form_for [@question, @answer] do |f| %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>

<% end %>

app/views/comments/_comment.html.erb
<div class= "comment">
    <%comments.each do |comment|%>
      <p>
        <%= comment.response %>
        <br>
        by <%= comment.user.username %>
     </p>
    <%end%>
  </div>

app/views/comments/_form.html.erb
<%= form_for [resource, comment] do |f|%>
  <%= f.text_field :response %>
  <%= f.submit%>
<% end %>

app/views/comments/new.html.erb
<%= render 'form', locals: {resource: params[:question_id], comment: @comment} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackover</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <header>
      <ul>
        <% if current_user %>
          <li><%= link_to 'Logout', session_path(current_user.id), method: "delete" %></li>
        <% else %>
          <li><%= link_to 'Login', new_session_path %></li>
          <li><%= link_to 'Signup', new_user_path %></li>
        <% end %>
      </ul>

      <ul>
        <li>
          <% if current_user %>
            Welcome <%= current_user.username %>
          <% end %>
        </li>
      </ul>
    </header>
<%= yield %>

</body>
</html>

app/views/questions/_question.html.erb
<li><%= link_to question.title, question_path(question) %></li>

app/views/questions/index.html.erb
<h2>
  <% if logged_in? %>
    <%= link_to 'Ask a new question', new_question_path %>
  <% end %>
</h2>

<h4>
  Recent questions
</h4>

<section>
 <%= render @questions %>
</section>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </p>
  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<h4>
  <li><%= link_to @question.title, question_path(@question) %></li>
  <li><%= @question.body %></li>
</h4>

<div>
  <%= link_to 'Add Comment', new_question_comment_path(@question) %>
</div>

<div>
  Comments:
  <%=render partial: "/comments/comment", locals: {comments: @question.comments}%>
</div>

  <%=link_to 'Add Answer', new_question_answer_path(@question)%>

<section>
  Answers:
  <%= render @answers %>
</section>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: users_path do |f| %>

  <% if @new_user.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@new_user.errors.count, "error") %> prohibited
       this user from being saved:
     </h2>
     <ul>
       <% @new_user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
  <%end%>

    Username: <%= f.text_field :username %>
    Password: <%= f.password_field :password %>
    Password Confirmation: <%= f.password_field :password_confirmation %>
    <%= f.submit "Submit" %>
<% end %>